const fs = require('fs');
const path = require('path');

const apiDir = path.join(__dirname, 'api');
const outputFile = path.join(__dirname, 'routes.js');

function scanRoutes(dir, basePath = '') {
  let routes = [];
  const files = fs.readdirSync(dir);

  for (const file of files) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      routes = routes.concat(scanRoutes(fullPath, path.join(basePath, file)));
    } else if (file.endsWith('.js')) {
      const relativePath = path.join(basePath, file).replace(/\\/g, '/');
      const importName = relativePath.replace(/[^a-zA-Z0-9]/g, '_');
      routes.push({
        path: `./api/${relativePath}`,
        name: importName
      });
    }
  }
  return routes;
}

const routes = scanRoutes(apiDir);

const content = `// This file is auto-generated by generate-routes.js
${routes.map(r => `import * as ${r.name} from '${r.path}';`).join('\n')}

export const routes = [
  ${routes.map(r => r.name).join(',\n  ')}
];
`;

fs.writeFileSync(outputFile, content);
console.log(`Generated ${outputFile} with ${routes.length} routes.`);
