// This file is auto-generated by generate-routes.js
import * as bluearchive_js from './api/bluearchive.js';
import * as deepseek_js from './api/deepseek.js';
import * as example_get_example_js from './api/example/get/example.js';
import * as example_post_sample_js from './api/example/post/sample.js';
import * as example_post_test_js from './api/example/post/test.js';
import * as mal_animeinfo_js from './api/mal-animeinfo.js';
import * as mal_animesearch_js from './api/mal-animesearch.js';
import * as mal_charainfo_js from './api/mal-charainfo.js';
import * as mal_charasearch_js from './api/mal-charasearch.js';
import * as mal_mangainfo_js from './api/mal-mangainfo.js';
import * as mal_mangasearch_js from './api/mal-mangasearch.js';
import * as mal_seasonalanime_js from './api/mal-seasonalanime.js';
import * as mal_topanime_js from './api/mal-topanime.js';
import * as spotifydl_js from './api/spotifydl.js';
import * as spotifydl2_js from './api/spotifydl2.js';
import * as tikdl_js from './api/tikdl.js';
import * as unidl_js from './api/unidl.js';
import * as ytmp3dl_js from './api/ytmp3dl.js';
import * as ytsearch_js from './api/ytsearch.js';

export const routes = [
  bluearchive_js,
  deepseek_js,
  example_get_example_js,
  example_post_sample_js,
  example_post_test_js,
  mal_animeinfo_js,
  mal_animesearch_js,
  mal_charainfo_js,
  mal_charasearch_js,
  mal_mangainfo_js,
  mal_mangasearch_js,
  mal_seasonalanime_js,
  mal_topanime_js,
  spotifydl_js,
  spotifydl2_js,
  tikdl_js,
  unidl_js,
  ytmp3dl_js,
  ytsearch_js
];
